### ISSUE TITLE
Support variable that is incremented each time it is used.

### ISSUE THREAD

**Issue by vetlek** [equinor/septic-config-generator#171]
This issue might on the side of the intended use of config generator and what is feasible to do. 

I want support for a jinja-variable that is incremented each time it is used and value maintained between templates etc. This is useful when using scg to generate mappings to OPC for KSpice.

Example:

```
{% set global ID_Incrementer = 1 %}
<KSIM_XREF>
    <Id>{{ ID_Incrementer }}</Id>
    <KsimName>Something</KsimName>
</KSIM_XREF>
<KSIM_XREF>
    <Id>{{ ID_Incrementer }}</Id>
    <KsimName>Something More</KsimName>
</KSIM_XREF>
```
would lead to the following in the generated file

```
<KSIM_XREF>
    <Id>1</Id>
    <KsimName>Something</KsimName>
</KSIM_XREF>
<KSIM_XREF>
    <Id>2</Id>
    <KsimName>Something More</KsimName>
</KSIM_XREF>
```

**Comment by einarsi** [comment]
That may unfortunately not be very straight-forward. Even "global" variables defined on command line and updated in one template are reset to their original value for the next template. Scoping is going to be a bit of an issue, especially since Minijinja does not seem to include support for manipulating dictionaries. 

I'll investigate a bit further, but don't hold your breath.

Note to self: Perhaps create a custom function that somehow updates an actual global variable? It can even exist "outside" of the template/Jinja scope as long as the function can access it. Alternatively: Can I get a return value from renders that includes (and then replaces the values of) globals?

**Comment by einarsi** [comment]
I have a crude POC working. It's currently just a function called `counter()` that increments its internal static variable by 1 and outputs the result whenever called. But it works and retains its value across templates. I think I can expand on this to make something more versatile. 

I guess being able to initialise the value and change it at will is a requirement? 
Do you see a use case for having more than one global counter at once?
