### ISSUE TITLE
SCG reads group mask wrong

### ISSUE THREAD

**Issue by palkitt** [equinor/septic-config-generator#190]
When group masks are made as formuals in Excel, SCG reads them wrong. Confirmed in versjon 2.5, 2.7
Example formula: =CONCAT(REPT("0";F2-1);"1";REPT("0";31-B2-F2);"1";REPT("0";B2-1))

**Comment by palkitt** [comment]
Works with v 1.0, not working with 2.0 and later

**Comment by einarsi** [comment]
As discussed:
- This is a bug (or feature?) in the underlying Calamine library which for Excel formulae interprets results such as "0000000000000000000000000000010" and "1000000000000000000000000000010" as numbers instead of as text. 
- In the first case the result becomes the integer 10.
- In the second case we get a negative number (32-bit int).
- I can probably add some logic that interprets the special case of only ones and zeros as text, but that may have adverse effects and is a bit of a convoluted band-aid solution.

Two ways to avoid the issue:
- Use the [bitmask custom function](https://github.com/equinor/septic-config-generator/blob/main/docs/Howto_SCG.md#bitmask-). This is easier and smoother than using concat() in Excel.
- Force the output of the Excel formula to be a text string by CONCAT()ing a " " to the start of the string.
